"""Evaluate multitask model and compare classification against baseline-v1."""
from __future__ import annotations
import argparse,csv,json,sys
from pathlib import Path
import numpy as np,tensorflow as tf
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report,mean_absolute_error,mean_squared_error
ROOT=Path(__file__).resolve().parents[1];CLASSES=['verde','maduro','pasado'];MAT={'unripe':15.,'ripe':60.,'overripe':85.,'rotten':100.};DAYS={'unripe':6.,'ripe':3.,'overripe':1.,'rotten':0.}
def main():
 p=argparse.ArgumentParser();p.add_argument('--manifest',default=ROOT/'data/dataset_v1/manifest.csv');p.add_argument('--model',default=ROOT/'models/banana_multitask_v1.keras');p.add_argument('--baseline-report',default=ROOT/'models/baseline_v1_evaluation.json');p.add_argument('--image-size',type=int,default=224);p.add_argument('--batch-size',type=int,default=32);a=p.parse_args()
 with open(a.manifest,encoding='utf-8',newline='') as f:rows=[r for r in csv.DictReader(f) if r['split']=='test']
 paths=[r['image_path'] for r in rows];truth=np.array([CLASSES.index(r['class_name']) for r in rows]);mat=np.array([MAT[r['original_state']] for r in rows]);days=np.array([DAYS[r['original_state']] for r in rows])
 def load(path):
  image=tf.io.decode_image(tf.io.read_file(path),channels=3,expand_animations=False);return tf.image.resize(tf.cast(image,tf.float32),(a.image_size,a.image_size))
 ds=tf.data.Dataset.from_tensor_slices(paths).map(load,num_parallel_calls=tf.data.AUTOTUNE).batch(a.batch_size);state,mat_pred,days_pred=tf.keras.models.load_model(a.model,compile=False).predict(ds,verbose=0);pred=state.argmax(1);mat_pred=mat_pred[:,0]*100;days_pred=days_pred[:,0]
 cls={'accuracy':float(accuracy_score(truth,pred)),'precision_macro':float(precision_score(truth,pred,average='macro',zero_division=0)),'recall_macro':float(recall_score(truth,pred,average='macro',zero_division=0)),'f1_macro':float(f1_score(truth,pred,average='macro',zero_division=0)),'confusion_matrix':confusion_matrix(truth,pred).tolist(),'classification_report':classification_report(truth,pred,target_names=CLASSES,output_dict=True,zero_division=0)}
 regression={'maturity_mae_pct':float(mean_absolute_error(mat,mat_pred)),'maturity_rmse_pct':float(mean_squared_error(mat,mat_pred)**.5),'days_mae':float(mean_absolute_error(days,days_pred)),'days_rmse':float(mean_squared_error(days,days_pred)**.5),'target_warning':'These are weak class-derived targets, not measured shelf-life labels.'}
 baseline=json.loads(Path(a.baseline_report).read_text(encoding='utf-8'));baseline_f1=baseline.get('f1_macro',baseline.get('classification_report',{}).get('macro avg',{}).get('f1-score',0.));result={'model':str(a.model),'test_images':len(rows),'classification':cls,'regression':regression,'baseline_v1_classification':{k:baseline[k] for k in ('accuracy','precision_macro','recall_macro')},'comparison':{'accuracy_delta':cls['accuracy']-baseline['accuracy'],'f1_macro_delta':cls['f1_macro']-baseline_f1},'note':'Dataset v1 and grouped test split unchanged. Days head is experimental until metadata with measured days is supplied.'}
 (ROOT/'models/banana_multitask_v1_evaluation.json').write_text(json.dumps(result,indent=2),encoding='utf-8');(ROOT/'models/banana_multitask_v1_evaluation.md').write_text(f'''# Multitask v1 evaluation\n\nTest images: **{len(rows)}**.\n\n| Metric | Multitask v1 | Baseline v1 | Delta |\n|---|---:|---:|---:|\n| Accuracy | {cls["accuracy"]:.4f} | {baseline["accuracy"]:.4f} | {result["comparison"]["accuracy_delta"]:+.4f} |\n| Precision macro | {cls["precision_macro"]:.4f} | {baseline["precision_macro"]:.4f} | â€” |\n| Recall macro | {cls["recall_macro"]:.4f} | {baseline["recall_macro"]:.4f} | â€” |\n| F1 macro | {cls["f1_macro"]:.4f} | {baseline_f1:.4f} | {result["comparison"]["f1_macro_delta"]:+.4f} |\n\n## RegresiÃ³n\n\n- Madurez MAE: **{regression["maturity_mae_pct"]:.2f} puntos porcentuales**; RMSE: **{regression["maturity_rmse_pct"]:.2f}**.\n- DÃ­as MAE: **{regression["days_mae"]:.2f} dÃ­as**; RMSE: **{regression["days_rmse"]:.2f}**.\n\n## Matriz de confusiÃ³n\n\nFilas reales, columnas predichas (`verde`, `maduro`, `pasado`):\n\n```text\n{cls["confusion_matrix"]}\n```\n\nLas mÃ©tricas de regresiÃ³n usan objetivos dÃ©biles derivados de la clase. Para uso real, incorporar `days_remaining_measured` y porcentaje medido en metadata por lote.\n''',encoding='utf-8');print(json.dumps(result,indent=2))
if __name__=='__main__':main()

